name: "Automatic PR Sync"
on:
  push:
    branches:
      - master
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  pr_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Sync all PRs
        uses: DiegoRamil/actions-pr-auto-update@cf3e3923551216c5ea744d3adbe32e7db38a3f0f
        with:
          token: ${{ secrets.GIT_TOKEN }}
          include_drafts: true
          exclude_labels: "skip auto update, still in progress"
