name: Go-test
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: go-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version: "1.24.x"

      - name: Build
        run: go build -v ./...

      - name: Test with the Go CLI
        run: go test ./...
