name: Run Nancy
on: [push]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version: "1.24.x"

      - name: Extract list of packages
        run: go list -json -m all > go.list

      - name: Run Nancy
        uses: sonatype-nexus-community/nancy-github-action@395e2fb168f674f96502e5652103d112899ea369
